# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""
Provider info for the placeholder provider template.

This file exists so the template can be linted and tested as real Python.
At generation time it is regenerated by ProviderCreator based on the
NewProviderRequest, so the contents here serve only as a reference.
"""

from __future__ import annotations


def get_provider_info():
    return {
        "package-name": "apache-airflow-providers-placeholder-provider",
        "name": "PlaceholderProvider",
        "description": "PlaceholderProvider provider",
        "integrations": [
            {
                "integration-name": "PlaceholderProvider",
                "external-doc-url": "https://example.com",
                "tags": ["service"],
            }
        ],
        "operators": [
            {
                "integration-name": "PlaceholderProvider",
                "python-modules": ["airflow.providers.placeholder_provider.operators.placeholder_provider"],
            }
        ],
        "sensors": [
            {
                "integration-name": "PlaceholderProvider",
                "python-modules": ["airflow.providers.placeholder_provider.sensors.placeholder_provider"],
            }
        ],
        "hooks": [
            {
                "integration-name": "PlaceholderProvider",
                "python-modules": ["airflow.providers.placeholder_provider.hooks.placeholder_provider"],
            }
        ],
        "triggers": [
            {
                "integration-name": "PlaceholderProvider",
                "python-modules": ["airflow.providers.placeholder_provider.triggers.placeholder_provider"],
            }
        ],
        "transfers": [
            {
                "source-integration-name": "PlaceholderProvider",
                "target-integration-name": "PlaceholderProvider",
                "python-module": "airflow.providers.placeholder_provider.transfers.placeholder_provider",
            }
        ],
        "bundles": [
            {
                "integration-name": "PlaceholderProvider",
                "python-modules": ["airflow.providers.placeholder_provider.bundles.placeholder_provider"],
            }
        ],
        "connection-types": [
            {
                "connection-type": "placeholder_provider",
                "hook-class-name": "airflow.providers.placeholder_provider.hooks.placeholder_provider.PlaceholderProviderHook",
            }
        ],
        "extra-links": [
            "airflow.providers.placeholder_provider.links.placeholder_provider.PlaceholderProviderLink"
        ],
        "filesystems": ["airflow.providers.placeholder_provider.fs.placeholder_provider"],
        "asset-uris": [
            {
                "schemes": ["placeholder_provider"],
                "handler": "airflow.providers.placeholder_provider.assets.placeholder_provider.sanitize_uri",
                "factory": "airflow.providers.placeholder_provider.assets.placeholder_provider.create_asset",
            }
        ],
        "dialects": [
            {
                "dialect-type": "placeholder_provider",
                "dialect-class-name": "airflow.providers.placeholder_provider.dialects.placeholder_provider.PlaceholderProviderDialect",
            }
        ],
        "secrets-backends": [
            "airflow.providers.placeholder_provider.secrets.placeholder_provider.PlaceholderProviderSecretsBackend"
        ],
        "logging": [
            "airflow.providers.placeholder_provider.log.placeholder_provider.PlaceholderProviderTaskHandler"
        ],
        "auth-backends": ["airflow.providers.placeholder_provider.auth_backend.placeholder_provider"],
        "auth-managers": [
            "airflow.providers.placeholder_provider.auth_managers.placeholder_provider.PlaceholderProviderAuthManager"
        ],
        "notifications": [
            "airflow.providers.placeholder_provider.notifications.placeholder_provider.PlaceholderProviderNotifier"
        ],
        "executors": [
            "airflow.providers.placeholder_provider.executors.placeholder_provider.PlaceholderProviderExecutor"
        ],
        "cli": [
            "airflow.providers.placeholder_provider.cli.definition.get_placeholder_provider_cli_commands"
        ],
        "task-decorators": [
            {
                "name": "placeholder_provider",
                "path": "airflow.providers.placeholder_provider.decorators.placeholder_provider.placeholder_provider_task",
            }
        ],
        "plugins": [
            {
                "name": "placeholder_provider",
                "plugin-class": "airflow.providers.placeholder_provider.plugins.placeholder_provider.PlaceholderProviderPlugin",
            }
        ],
        "queues": [
            {
                "name": "placeholder_provider",
                "message-queue-class": "airflow.providers.placeholder_provider.queues.placeholder_provider.PlaceholderProviderMessageQueue",
            }
        ],
        "config": {
            "placeholder_provider": {
                "description": "PlaceholderProvider provider configuration",
                "options": {
                    "api_key": {
                        "description": "API key for PlaceholderProvider",
                        "version_added": "0.1.0",
                        "type": "string",
                        "example": "my-api-key",
                        "default": "",
                        "sensitive": True,
                    }
                },
            }
        },
    }
