#!/usr/bin/env python
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""
Record what Python's serializer makes of the shared fixtures in test_dags.json.

The recorded output is the reference ``conformance.test.ts`` compares the
TypeScript serializer against, so that a change to either serializer has to be
justified against the other. Regenerate it with::

    uv run --project airflow-core python ts-sdk/tests/conformance/serialize_python.py

``--check`` re-records into memory and fails when the committed file has drifted,
which is what CI would run. ``--verify <file>`` takes a ``DagFileParsingResult``
produced by the TypeScript serializer and pushes every Dag in it back through
Airflow's own deserializer, which is the property that actually matters: the
scheduler has to be able to read what a TypeScript bundle sends.
"""

from __future__ import annotations

import argparse
import datetime
import json
import sys
from pathlib import Path
from typing import Any

from airflow.sdk import DAG, BaseOperator
from airflow.serialization.serialized_objects import DagSerialization

HERE = Path(__file__).parent
FIXTURES = HERE / "test_dags.json"
RECORDED = HERE / "serialized_python.json"


class NoopOperator(BaseOperator):
    """Stands in for a TypeScript task: a task with no Python behaviour."""

    def execute(self, context):
        return None


def decode(value: Any) -> Any:
    """Turn the fixture's tagged scalars into the Python objects DAG() expects."""
    if isinstance(value, dict):
        if "__datetime" in value:
            return datetime.datetime.fromisoformat(value["__datetime"])
        if "__timedelta" in value:
            return datetime.timedelta(seconds=value["__timedelta"])
        return {key: decode(item) for key, item in value.items()}
    if isinstance(value, list):
        return [decode(item) for item in value]
    return value


def build_dag(fixture: dict[str, Any]) -> DAG:
    dag = DAG(fixture["dag_id"], **{key: decode(v) for key, v in fixture["spec"].items()})
    for task in fixture["tasks"]:
        NoopOperator(
            task_id=task["task_id"],
            dag=dag,
            **{key: decode(v) for key, v in task["spec"].items()},
        )
    for task in fixture["tasks"]:
        for upstream in task["upstream"]:
            dag.get_task(upstream) >> dag.get_task(task["task_id"])
    return dag


def serialize_all() -> dict[str, Any]:
    fixtures = json.loads(FIXTURES.read_text())
    return {
        "$comment": (
            "Generated by serialize_python.py from test_dags.json — do not edit by hand. "
            "`fileloc` is dropped: it is the path of the Python file that declared the "
            "fixture, which has no counterpart in a TypeScript bundle."
        ),
        "dags": {
            fixture["dag_id"]: drop_fileloc(DagSerialization.to_dict(build_dag(fixture)))
            for fixture in fixtures["dags"]
        },
    }


def drop_fileloc(serialized: dict[str, Any]) -> dict[str, Any]:
    for key in ("fileloc", "relative_fileloc", "_processor_dags_folder"):
        serialized["dag"].pop(key, None)
    return serialized


def verify_typescript_output(path: Path) -> int:
    """Push a TypeScript DagFileParsingResult through Airflow's deserializer."""
    payload = json.loads(path.read_text())
    entries = payload["serialized_dags"]
    if not entries:
        print(f"{path}: no serialized_dags to verify", file=sys.stderr)
        return 1
    for entry in entries:
        data = entry["data"]
        DagSerialization.validate_schema(data)
        dag = DagSerialization.from_dict(data)
        print(
            f"  {dag.dag_id}: schema OK, "
            f"timetable={type(dag.timetable).__name__}, "
            f"tasks={sorted(dag.task_dict)}"
        )
    print(f"{len(entries)} Dag(s) validated and deserialized")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the recorded output drifted")
    parser.add_argument("--verify", type=Path, help="deserialize a TypeScript parsing result")
    args = parser.parse_args()

    if args.verify:
        return verify_typescript_output(args.verify)

    rendered = json.dumps(serialize_all(), indent=2, sort_keys=True) + "\n"
    if args.check:
        if not RECORDED.exists() or RECORDED.read_text() != rendered:
            print(
                f"{RECORDED} is out of date; re-run {Path(__file__).name} to record it",
                file=sys.stderr,
            )
            return 1
        print(f"{RECORDED} is up to date")
        return 0

    RECORDED.write_text(rendered)
    print(f"wrote {RECORDED}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
