// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Package conformance declares which Airflow Language SDK conformance dimensions the Go SDK
// implements. Capabilities is the single source of truth for go-sdk/capabilities.json, which is
// generated by cmd/dump-capabilities and consumed by the compatibility-matrix prek hooks. The
// normative meaning of each dimension is defined in contributing-docs/30_new_language_sdk.rst.
package conformance

import "github.com/apache/airflow/go-sdk/pkg/execution"

// Entry records whether the SDK supports one conformance dimension.
type Entry struct {
	Supported bool    `json:"supported"`
	Since     *string `json:"since"`
	Note      string  `json:"note"`
}

// Document is the machine-readable capability manifest serialised to capabilities.json.
type Document struct {
	SDK                     string           `json:"sdk"`
	SupervisorSchemaVersion string           `json:"supervisor_schema_version"`
	MinAirflowVersion       string           `json:"min_airflow_version"`
	States                  map[string]Entry `json:"states"`
	Capabilities            map[string]Entry `json:"capabilities"`
}

const minAirflowVersion = "3.3"

func yes(note string) Entry {
	since := minAirflowVersion
	return Entry{Supported: true, Since: &since, Note: note}
}

func no(note string) Entry {
	return Entry{Supported: false, Note: note}
}

// Capabilities is the source of truth for what the Go SDK supports. Update it when the runtime
// gains or loses a conformance dimension, then regenerate capabilities.json.
var Capabilities = Document{
	SDK:                     "go",
	SupervisorSchemaVersion: execution.SupervisorSchemaVersion,
	MinAirflowVersion:       minAirflowVersion,
	// The task runner terminates a task with SucceedTask, TaskState (failed/removed), or RetryTask.
	// It does not yet emit skipped, DeferTask, RescheduleTask, or AwaitInputTask.
	States: map[string]Entry{
		"success":           yes(""),
		"failed":            yes(""),
		"up_for_retry":      yes("RetryTask"),
		"skipped":           no("runtime does not emit TaskState skipped yet"),
		"deferred":          no("runtime does not emit DeferTask yet"),
		"up_for_reschedule": no("runtime does not emit RescheduleTask yet"),
		"awaiting_input":    no("runtime does not emit AwaitInputTask yet"),
		"removed":           yes(""),
	},
	// Runtime capabilities reflect the task-facing CoordinatorClient surface over the comm socket;
	// native-Dag authoring is not implemented yet, so every native capability is unsupported.
	Capabilities: map[string]Entry{
		"mixed-lang-stub-target": yes("@task.stub"),
		"task-logging":           yes("slog records streamed over the logs socket"),
		"xcom-read-write":        yes("PushXCom / GetXCom"),
		"connection-read":        yes("GetConnection"),
		"variable-read-write":    no("GetVariable only; no write over the comm socket yet"),
		"self-contained-bundle":  yes("AFBNDL01 native binary via airflow-go-pack"),
		"task-state-store":       no("no task-facing state-store API yet"),
		"asset-state-store":      no("no task-facing state-store API yet"),
		"asset-event-emit":       no("runtime does not emit asset events yet"),
		"asset-event-read":       no("no task-facing asset-event API yet"),
		"native-dag-authoring":   no("native Dag authoring not implemented yet"),
		"task-args":              no(""),
		"dag-params":             no(""),
		"taskflow-dependencies":  no(""),
		"branching":              no(""),
		"dag-test":               no(""),
		"task-group":             no(""),
		"dynamic-task-mapping":   no(""),
		"asset-inlets-outlets":   no(""),
		"asset-scheduling":       no(""),
		"object-store":           no("no object-storage API yet"),
	},
}
